### ISSUE TITLE
Probleme mit MooTools

### ISSUE THREAD

**Issue by Schmidty2** [eS-IT/esitbeforeafter#1]
Hallo,
wenn im Seitenlayout die MooTools aktiviert sind, läuft die Erweiterung nicht mehr, die Bilder werden untereinander angezeigt.
MooTools benötige ich für die Erweiterung calendarfield.

Einen Link zur Testseite inkl. FTP- und Backendzugang kann zur Verfügung gestellt werden.

**Comment by eS-IT** [comment]
Ich habe die Kompatibilität mit mooTools hergestellt. Nun sollte es funktionieren.
